version: 2

updates:
- package-ecosystem: npm
  directory: "/ui"
  schedule:
    interval: weekly
  commit-message:
    prefix: "ui"
  ignore:
    - dependency-name: "vue-fragment"
- package-ecosystem: gomod
  directory: "/agent"
  schedule:
    interval: weekly
  commit-message:
    prefix: "agent"
  ignore:
      - dependency-name: "github.com/shellhub-io/shellhub"
- package-ecosystem: gomod
  directory: "/api"
  schedule:
    interval: weekly
  commit-message:
    prefix: "api"
  ignore:
      - dependency-name: "github.com/shellhub-io/shellhub"
- package-ecosystem: gomod
  directory: "/ssh"
  schedule:
    interval: weekly
  commit-message:
    prefix: "ssh"
  ignore:
      - dependency-name: "github.com/shellhub-io/shellhub"
- package-ecosystem: gomod
  directory: "/cli"
  schedule:
    interval: weekly
  commit-message:
    prefix: "cli"
  ignore:
      - dependency-name: "github.com/shellhub-io/shellhub"
