output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true

linters:
  disable-all: true
  enable:
    - gofmt
    - revive
    - gosimple
    - govet
    - ineffassign
    - exportloopref
    - staticcheck
    - unconvert
    - unused
    - misspell
    - goimports
    - typecheck
    - errcheck
    - whitespace
    - depguard
    - stylecheck
    - nlreturn
    - nilerr

linters-settings:
  staticcheck:
    checks: ["all", "-SA1029"]
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      - github.com/satori/go.uuid
      - github.com/dgrijalva/jwt-go
    packages-with-error-message:
      - github.com/satori/go.uuid: "Uuid generation is only allowed using 'github.com/shellhub-io/shellhub/pkg/uuid'"
      - github.com/dgrijalva/jwt-go: "dgrijalva/jwt-go is deprecated please use 'github.com/golang-jwt/jwt'"
  whitespace:
    multi-if: true
    multi-func: true
  govet:
    disable:
      - composites
