output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true

linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      - github.com/satori/go.uuid
    packages-with-error-message:
      - github.com/satori/go.uuid: "Uuid generation is only allowed using 'github.com/shellhub-io/shellhub/pkg/uuid'"

linters:
  enable:
    - depguard

issues:
  exclude:
    # govet: unkeyed fields use
    - composite

  exclude-rules:
    - linters:
        - staticcheck

      # TODO: We should rework the code to avoid this issue; this will be done
      # during more deep code rework so for now, we'll skip it.
      text: "SA1029:"

    - linters:
        - govet

      # validate is unknown but it is a valid tag.
      text: "structtag: struct field tag .* validate:"
