ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 1
warningCode = 1

[rule.atomic]
[rule.blank-imports]
[rule.bool-literal-in-expr]
[rule.call-to-gc]
[rule.confusing-results]
[rule.constant-logical-expr]
[rule.context-as-argument]
[rule.deep-exit]
[rule.dot-imports]
[rule.duplicated-imports]
[rule.empty-block]
[rule.empty-lines]
[rule.error-naming]
[rule.error-return]
[rule.error-strings]
[rule.errorf]
[rule.get-return]
[rule.if-return]
[rule.imports-blacklist]
[rule.increment-decrement]
[rule.indent-error-flow]
[rule.modifies-parameter]
[rule.modifies-value-receiver]
[rule.package-comments]
[rule.range-val-address]
[rule.range-val-in-closure]
[rule.range]
[rule.receiver-naming]
[rule.redefines-builtin-id]
[rule.string-of-int]
[rule.superfluous-else]
[rule.time-naming]
[rule.unexported-return]
[rule.unreachable-code]
[rule.unused-parameter]
[rule.var-declaration]
[rule.var-naming]
[rule.waitgroup-by-value]

# Below are lints we ought to enable in future and fix the respective errors.
#[rule.add-constant]
#[rule.bare-return]
#[rule.confusing-naming]
#[rule.context-keys-type]
#[rule.exported]
#[rule.flag-parameter]
#[rule.import-shadowing]
#[rule.struct-tag]
#[rule.unhandled-error]
#[rule.unnecessary-stmt]
#[rule.unused-receiver]
