version: '3.7'

services:
  ssh:
    image: shellhubio/ssh:${SHELLHUB_VERSION}
    environment:
      - PRIVATE_KEY=/run/secrets/ssh_private_key
      - SHELLHUB_HOSTED=${SHELLHUB_HOSTED}
    ports:
      - "${SHELLHUB_SSH_PORT}:2222"
    secrets:
      - ssh_private_key
  api:
    image: shellhubio/api:${SHELLHUB_VERSION}
    environment:
      - PRIVATE_KEY=/run/secrets/api_private_key
      - PUBLIC_KEY=/run/secrets/api_public_key
    depends_on:
      - mongo
    links:
      - mongo
    secrets:
      - api_private_key
      - api_public_key
  ui:
    image: shellhubio/ui:${SHELLHUB_VERSION}
    environment:
      - SHELLHUB_HOSTED=${SHELLHUB_HOSTED}
    depends_on:
      - api
  gateway:
    image: shellhubio/gateway:${SHELLHUB_VERSION}
    environment:
      - SHELLHUB_VERSION=${SHELLHUB_VERSION}
      - SHELLHUB_SSH_PORT=${SHELLHUB_SSH_PORT}
      - SHELLHUB_PROXY=${SHELLHUB_PROXY}
    depends_on:
      - api
      - ui
    ports:
      - "${SHELLHUB_HTTP_PORT}:80"
  mongo:
    image: mongo:3.4.19

secrets:
  ssh_private_key:
    file: ./ssh_private_key
  api_private_key:
    file: ./api_private_key
  api_public_key:
    file: ./api_public_key
