services:
  api:
    image: registry.infra.ossystems.io/cache/shellhubio/api:${SHELLHUB_VERSION}

  ui:
    image: registry.infra.ossystems.io/cache/shellhubio/ui:${SHELLHUB_VERSION}

  gateway:
    image: registry.infra.ossystems.io/cache/shellhubio/gateway:${SHELLHUB_VERSION}

  cli:
    image: registry.infra.ossystems.io/cache/shellhubio/cli:${SHELLHUB_VERSION}

  mongo:
    image: registry.infra.ossystems.io/cache/mongo:4.4.8

  redis:
    image: registry.infra.ossystems.io/cache/redis

  ssh:
    image: registry.infra.ossystems.io/cache/shellhubio/ssh:${SHELLHUB_VERSION}
    environment:
      - RECORD_URL=cloud-api:8080
      - BILLING_URL=billing-api:8080
  cloud-api:
    image: registry.infra.ossystems.io/shellhub/cloud-api:${SHELLHUB_VERSION}
    restart: unless-stopped
    environment:
      - EMAIL_API_KEY=${SHELLHUB_EMAIL_API_KEY}
      - EMAIL_FROM_NAME=${SHELLHUB_EMAIL_FROM_NAME}
      - EMAIL_FROM_ADDRESS=${SHELLHUB_EMAIL_FROM_ADDRESS}
    networks:
      - shellhub
  admin-api:
    image: registry.infra.ossystems.io/shellhub/admin-api:${SHELLHUB_VERSION}
    restart: unless-stopped
    environment:
      - ADMIN_API_USERNAME=${SHELLHUB_ENTERPRISE_ADMIN_USERNAME}
      - ADMIN_API_PASSWORD=${SHELLHUB_ENTERPRISE_ADMIN_PASSWORD}
    secrets:
      - api_private_key
      - api_public_key
    networks:
      - shellhub
  dashboard:
    image: registry.infra.ossystems.io/shellhub/dashboard:${SHELLHUB_VERSION}
    restart: unless-stopped
    networks:
      - shellhub
