version: '3.7'

services:
  ssh:
    image: ssh
    build:
      context: .
      dockerfile: ssh/Dockerfile
      target: development
      network: host
      args:
        - GOPROXY=${SHELLHUB_GOPROXY}
    volumes:
      - ./ssh:/go/src/github.com/shellhub-io/shellhub/ssh
      - ./pkg:/go/src/github.com/shellhub-io/shellhub/pkg
      - ./.golangci.yaml:/.golangci.yaml
    environment:
      - SHELLHUB_ENTERPRISE=${SHELLHUB_ENTERPRISE}
      - SHELLHUB_CLOUD=${SHELLHUB_CLOUD}
      - SHELLHUB_BILLING=${SHELLHUB_BILLING}
  api:
    image: api
    build:
      context: .
      dockerfile: api/Dockerfile
      target: development
      network: host
      args:
        - GOPROXY=${SHELLHUB_GOPROXY}
    volumes:
      - ./api:/go/src/github.com/shellhub-io/shellhub/api
      - ./pkg:/go/src/github.com/shellhub-io/shellhub/pkg
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.golangci.yaml:/.golangci.yaml
    environment:
      - SHELLHUB_ENTERPRISE=${SHELLHUB_ENTERPRISE}
      - SHELLHUB_CLOUD=${SHELLHUB_CLOUD}
  ui:
    image: ui
    build:
      context: .
      dockerfile: ui/Dockerfile
      target: development
      network: host
      args:
        - NPM_CONFIG_REGISTRY=${SHELLHUB_NPM_REGISTRY}
    volumes:
      - ./ui:/src
    environment:
      - SHELLHUB_ENTERPRISE=${SHELLHUB_ENTERPRISE}
  gateway:
    image: gateway
    build:
      context: .
      dockerfile: gateway/Dockerfile
    environment:
      - SHELLHUB_VERSION=latest
      - SHELLHUB_ENV=${SHELLHUB_ENV}
  agent:
    image: agent
    restart: unless-stopped
    build:
      context: .
      dockerfile: agent/Dockerfile
      target: development
      network: host
      args:
        - SHELLHUB_VERSION=latest
        - GOPROXY=${SHELLHUB_GOPROXY}

    privileged: true
    network_mode: host
    pid: host
    environment:
      - SHELLHUB_SERVER_ADDRESS=http://localhost:${SHELLHUB_HTTP_PORT}
      - SHELLHUB_PRIVATE_KEY=/go/src/github.com/shellhub-io/shellhub/agent/shellhub.key
      - SHELLHUB_TENANT_ID=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      - SHELLHUB_VERSION=${SHELLHUB_VERSION}
    volumes:
      - ./agent:/go/src/github.com/shellhub-io/shellhub/agent
      - ./pkg:/go/src/github.com/shellhub-io/shellhub/pkg
      - /:/host
      - /dev:/dev
      - /etc/passwd:/etc/passwd
      - /etc/group:/etc/group
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.golangci.yaml:/.golangci.yaml
    depends_on:
      - api
      - ssh
      - gateway
  cli:
    image: cli
    build:
      context: .
      dockerfile: cli/Dockerfile
      target: development
    entrypoint: /entrypoint.sh
    volumes:
      - ./cli:/go/src/github.com/shellhub-io/shellhub/cli
      - ./pkg:/go/src/github.com/shellhub-io/shellhub/pkg
      - ./api:/go/src/github.com/shellhub-io/shellhub/api
      - ./.golangci.yaml:/.golangci.yaml
    depends_on:
    - api
    - mongo
  autossl:
    image: tianon/true
  openapi:
    image: openapi
    build:
      context: .
      dockerfile: openapi/Dockerfile
      target: openapi
    volumes:
      - ./openapi:/openapi
    networks:
      - shellhub
