version: '3.7'

services:
  ssh:
    environment:
      - RECORD_URL=cloud-api:8080
      - BILLING_URL=billing-api:8080
  cloud-api:
    image: registry.infra.ossystems.io/shellhub/cloud-api:${SHELLHUB_VERSION}
    restart: unless-stopped
    environment:
      - API_STORE_CACHE=${SHELLHUB_STORE_CACHE}
    networks:
      - shellhub
  admin-api:
    image: registry.infra.ossystems.io/shellhub/admin-api:${SHELLHUB_VERSION}
    restart: unless-stopped
    environment:
      - ADMIN_API_USERNAME=${SHELLHUB_ENTERPRISE_ADMIN_USERNAME}
      - ADMIN_API_PASSWORD=${SHELLHUB_ENTERPRISE_ADMIN_PASSWORD}
      - ADMIN_API_STORE_CACHE=${SHELLHUB_STORE_CACHE}
    secrets:
      - api_private_key
      - api_public_key
    networks:
      - shellhub
  dashboard:
    image: registry.infra.ossystems.io/shellhub/dashboard:${SHELLHUB_VERSION}
    restart: unless-stopped
    networks:
      - shellhub
