version: '3.7'

services:
  ssh:
    image: shellhubio/shellhub-ssh:${SHELLHUB_VERSION}
    environment:
      - PRIVATE_KEY=/run/secrets/ssh_private_key
    depends_on:
      - emq
    links:
      - emq
    ports:
      - "${SHELLHUB_SSH_PORT}:2222"
    secrets:
      - ssh_private_key
  emq:
    image: emqx/emqx:v3.1.1
    environment:
      - EMQX_NAME=emq
      - EMQX_HOST=127.0.0.1
      - EMQX_LISTENER__TCP__EXTERNAL=1883
      - EMQX_LOADED_PLUGINS=emqx_management,emqx_dashboard,emqx_auth_http,emqx_web_hook
      - EMQX_LOG__CONSOLE__LEVEL=debug
      - EMQX_AUTH__HTTP__AUTH_REQ=http://api:8080/internal/mqtt/auth
      - EMQX_AUTH__HTTP__AUTH_REQ__method=get
      - EMQX_AUTH__HTTP__AUTH_REQ__params=username=%u,password=%P,ipaddr=%a
      - EMQX_AUTH__HTTP__ACL_REQ=http://api:8080/internal/mqtt/acl
      - EMQX_AUTH__HTTP__ACL_REQ__METHOD=get
      - EMQX_AUTH__HTTP__ACL_REQ__PARAMS=access=%A,username=%u,topic=%t,ipaddr=%a
      - EMQX_AUTH__HTTP__ACL_NOMATCH=deny
      - EMQX_AUTH__HTTP__SUPER_REQ=http://api:8080/internal/mqtt/superuser
      - EMQX_AUTH__HTTP__SUPER_REQ__method=get
      - EMQX_AUTH__HTTP__SUPER_REQ__params=username=%u,password=%P,ipaddr=%a
      - EMQX_WEB__HOOK__API__URL=http://api:8080/internal/mqtt/webhook
    links:
      - api
    ports:
    - target: 1883
      published: 1883
      protocol: tcp
      mode: host
    - target: 18083
      published: 18083
      protocol: tcp
      mode: host
  api:
    image: shellhubio/shellhub-api:${SHELLHUB_VERSION}
    environment:
      - PRIVATE_KEY=/run/secrets/api_private_key
      - PUBLIC_KEY=/run/secrets/api_public_key
    depends_on:
      - mongo
    links:
      - mongo
    secrets:
      - api_private_key
      - api_public_key
  ui:
    image: shellhubio/shellhub-ui:${SHELLHUB_VERSION}
    depends_on:
      - api
  gateway:
    image: shellhubio/shellhub-gateway:${SHELLHUB_VERSION}
    environment:
      - SHELLHUB_VERSION=${SHELLHUB_VERSION}
      - SHELLHUB_SSH_PORT=${SHELLHUB_SSH_PORT}
    depends_on:
      - api
      - ui
    ports:
      - '80:80'
  mongo:
    image: mongo:3.4.19

secrets:
  ssh_private_key:
    file: ./ssh_private_key
  api_private_key:
    file: ./api_private_key
  api_public_key:
    file: ./api_public_key
