version: '3.7'

services:
  ssh:
    image: shellhubio/ssh:${SHELLHUB_VERSION}
    restart: unless-stopped
    environment:
      - PRIVATE_KEY=/run/secrets/ssh_private_key
      - SHELLHUB_ENTERPRISE=${SHELLHUB_ENTERPRISE}
      - RECORD_URL=${SHELLHUB_RECORD_URL}
      - WEBHOOK_URL=${SHELLHUB_WEBHOOK_URL}
      - WEBHOOK_PORT=${SHELLHUB_WEBHOOK_PORT}
      - WEBHOOK_SCHEME=${SHELLHUB_WEBHOOK_SCHEME}
    ports:
      - "${SHELLHUB_SSH_PORT}:2222"
    secrets:
      - ssh_private_key
    networks:
      - shellhub
  api:
    image: shellhubio/api:${SHELLHUB_VERSION}
    restart: unless-stopped
    environment:
      - PRIVATE_KEY=/run/secrets/api_private_key
      - PUBLIC_KEY=/run/secrets/api_public_key
      - SHELLHUB_ENTERPRISE=${SHELLHUB_ENTERPRISE}
      - STORE_CACHE=${SHELLHUB_STORE_CACHE}
    depends_on:
      - mongo
    links:
      - mongo
    secrets:
      - api_private_key
      - api_public_key
    networks:
      - shellhub
  ui:
    image: shellhubio/ui:${SHELLHUB_VERSION}
    restart: unless-stopped
    environment:
      - SHELLHUB_ENTERPRISE=${SHELLHUB_ENTERPRISE}
      - SHELLHUB_CLOUD=${SHELLHUB_CLOUD}
    depends_on:
      - api
    networks:
      - shellhub
  gateway:
    image: shellhubio/gateway:${SHELLHUB_VERSION}
    restart: unless-stopped
    environment:
      - SHELLHUB_VERSION=${SHELLHUB_VERSION}
      - SHELLHUB_SSH_PORT=${SHELLHUB_SSH_PORT}
      - SHELLHUB_PROXY=${SHELLHUB_PROXY}
      - SHELLHUB_ENTERPRISE=${SHELLHUB_ENTERPRISE}
    depends_on:
      - api
      - ui
    networks:
      - shellhub
  cli:
    image: shellhubio/cli:${SHELLHUB_VERSION}
    restart: unless-stopped
    environment:
      - STORE_CACHE=${SHELLHUB_STORE_CACHE}
    depends_on:
      - api
      - mongo
    networks:
      - shellhub
  mongo:
    image: mongo:4.4.4
    restart: unless-stopped
    networks:
      - shellhub

secrets:
  ssh_private_key:
    file: ./ssh_private_key
  api_private_key:
    file: ./api_private_key
  api_public_key:
    file: ./api_public_key

networks:
  shellhub:
    name: shellhub_network
