openapi: 3.0.2
$ref: spec/shared/common-openapi.yaml
paths:
  $ref: community-openapi.yaml#/paths
  /api/firewall/rules:
    $ref: spec/resources/firewall/rules.yaml
  '/api/firewall/rules/{id}':
    $ref: spec/resources/firewall/rules_id.yaml
  '/api/firewall/rules/{id}/tags':
    $ref: spec/resources/firewall/rules_id_tags.yaml
  '/api/sessions/{uid}/play':
    $ref: spec/resources/sessions/play.yaml
  '/api/sessions/{uid}/record':
    $ref: spec/resources/sessions/record_del.yaml
  /api/register:
    $ref: spec/resources/user/register.yaml
  /api/user/resend_email:
    $ref: spec/resources/user/resend_email.yaml
  '/api/user/{uid}/update_password':
    $ref: spec/resources/user/uid_update_password.yaml
  /api/user/validation_account:
    $ref: spec/resources/user/validation_account.yaml
  /api/user/recover_password:
    $ref: spec/resources/user/recover_password.yaml