openapi: 3.0.2
info:
  title: ShellHub Community
  description: |
    ShellHub Community documentation.
    
    It documents all routes provided by ShellHub Community.
  contact:
    email: contato@ossystems.com.br
  license:
    name: Apache License 2.0
    url: https://github.com/shellhub-io/shellhub/blob/master/LICENSE.md
  version: 1.0.0
servers:
  - url: http://localhost
    description: ShellHub API server
components:
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /api/login:
    $ref: spec/paths/api@login.yaml
  /api/auth/user:
    $ref: spec/paths/api@login.yaml
  /api/devices/auth:
    $ref: spec/paths/api@devices@auth.yaml
  /api/auth/device:
    $ref: spec/paths/api@auth@device.yaml
  /api/auth/ssh:
    $ref: spec/paths/api@auth@ssh.yaml
  /api/auth/token/{tenant}:
    $ref: spec/paths/api@auth@token@{tenant}.yaml
  /api/token/{tenant}:
    $ref: spec/paths/api@token@{tenant}.yaml
  /api/devices/{uid}/accept:
    $ref: spec/paths/api@devices@{uid}@accept.yaml
  /api/users/{id}/data:
    $ref: spec/paths/api@users@{id}@data.yaml
  /api/users/{id}/password:
    $ref: spec/paths/api@users@{id}@password.yaml
  /api/users/security/{id}:
    $ref: spec/paths/api@users@security@{id}.yaml
  /api/users/security:
    $ref: spec/paths/api@users@security.yaml
  /api/devices:
    $ref: spec/paths/api@devices.yaml
  /api/devices/{uid}:
    $ref: spec/paths/api@devices@{uid}.yaml
  /api/devices/{uid}/{status}:
    $ref: spec/paths/api@devices@{uid}@{status}.yaml
  /api/sessions:
    $ref: spec/paths/api@sessions.yaml
  /api/sessions/{uid}:
    $ref: spec/paths/api@sessions@{uid}.yaml
  /api/sshkeys/public-keys:
    $ref: spec/paths/api@sshkeys@public-keys.yaml
  /api/sshkeys/public-keys/{fingerprint}:
    $ref: spec/paths/api@sshkeys@public-keys@{fingerprint}.yaml
  /api/sshkeys/public-keys/{fingerprint}/tags:
    $ref: spec/paths/api@sshkeys@public-keys@{fingerprint}@tags.yaml
  /api/sshkeys/public-keys/{fingerprint}/tags/{name}:
    $ref: spec/paths/api@sshkeys@public-keys@{fingerprint}@tags@{name}.yaml
  /api/stats:
    $ref: spec/paths/api@stats.yaml
  /api/namespaces:
    $ref: spec/paths/api@namespaces.yaml
  /api/namespaces/{tenant}:
    $ref: spec/paths/api@namespaces@{tenant}.yaml
  /api/namespaces/{tenant}/members:
    $ref: spec/paths/api@namespaces@{tenant}@members.yaml
  /api/namespaces/{tenant}/members/{uid}:
    $ref: spec/paths/api@namespaces@{tenant}@members@{uid}.yaml
  /api/devices/{uid}/tags:
    $ref: spec/paths/api@devices@{uid}@tags.yaml
  /api/devices/{uid}/tags/{name}:
    $ref: spec/paths/api@devices@{uid}@tags@{name}.yaml
  /api/tags:
    $ref: spec/paths/api@tags.yaml
  /api/tags/{name}:
    $ref: spec/paths/api@tags@{name}.yaml
