global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":80"

api:
  insecure: true
  dashboard: true

experimental:
  localPlugins:
    requestid-plugin:
      moduleName: github.com/shellhub-io/shellhub/traefik/requestid-plugin

providers:
  file:
    directory: /etc/traefik/conf.d
    watch: true

accessLog:
  format: json
