name: dependabot_pr

on:
  pull_request:
    branches: [master]
    paths:
      - '**/go.mod'
      - '**/go.sum'

jobs:
  go-mod-tidy:
    if: contains(github.head_ref, 'dependabot/go_modules/') && github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Update go.sum
        run: |
          # Run go mod tidy for every sub-project
          for i in $(seq 1 5); do
              for dir in cli api agent ssh; do
                  (cd $dir && go mod tidy)
              done
          done

          # Run go mod tidy for root project
          go mod tidy
      - name: Create diff artifact
        run: |
          git diff > /tmp/diff
      - uses: actions/upload-artifact@v2
        with:
          name: diff
          path: /tmp/diff
          retention-days: 1
