name: dependabot_pr

on:
  pull_request:
    branches: [master]
    action: [opened, synchronize, reopened]
    paths:
      - '**/go.mod'
      - '**/go.sum'

jobs:
  post-update:
    permissions:
      contents: write # to push code in repo (stefanzweifel/git-auto-commit-action)

  go-mod-tidy:
    name: Update Go modules
    if: contains(github.head_ref, 'dependabot/go_modules/') && github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
          ref: ${{ github.head_ref }}
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Run prepare-release script to update Go modules
        run: |
          ./devscripts/prepare-release
      - name: Get last commit message
        id: last-commit-message
        run: |
          echo "msg=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.event.workflow_run.head_branch }}
          file_pattern: '**/go.mod **/go.sum'
          commit_message: ${{ steps.last-commit-message.outputs.msg }}
          commit_options: '--amend --no-edit'
          push_options: '--force'
          skip_fetch: true
