name: dependabot_pr

on:
  pull_request:
    branches: [master]
    paths:
      - '**/go.mod'
      - '**/go.sum'

jobs:
  go-mod-tidy:
    if: contains(github.head_ref, 'dependabot/go_modules/') && github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Run prepare-release script to update Go modules
        run: |
          ./devscripts/prepare-release
      - name: Create diff artifact
        run: |
          git diff > /tmp/diff
      - uses: actions/upload-artifact@v2
        with:
          name: diff
          path: /tmp/diff
          retention-days: 1
