name: docker-build-validation

on:
  push:
    branches: [ master ]
    paths:
    - '**Dockerfile**'

  pull_request:
    branches: [ master ]
    paths:
    - '**Dockerfile'

jobs:

  docker-build:
    name: docker-build

    strategy:
      fail-fast: false
      matrix:
        project: [ api, ssh ]

    runs-on: ubuntu-latest

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      working-directory: ${{ matrix.project }}
      run: go mod download

    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - uses: docker/build-push-action@v1
      if: matrix.project != 'agent'
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: shellhubio/${{ matrix.project }}
        tags: latest
        push: false
        dockerfile: ${{ matrix.project }}/Dockerfile