name: docker-build

on:
  push:
    branches: [master]
    paths:
      - "**Dockerfile**"

  pull_request:
    branches: [master]
    paths:
      - "**Dockerfile"

jobs:
  build:
    name: Build '${{ matrix.project }}' Docker container

    strategy:
      fail-fast: false
      matrix:
        project: [api, ssh, gateway, ui, cli]

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build '${{ matrix.project }}' Docker container
        uses: docker/build-push-action@v5
        with:
          tags: shellhubio/${{ matrix.project }}:latest
          push: false
          file: ${{ matrix.project }}/Dockerfile
