name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build

    strategy:
      matrix:
        project: [ api,  agent,  pkg,  ssh ]

    runs-on: ubuntu-latest

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      working-directory: ${{ matrix.project }}
      run: go mod download

    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Run gofmt -s
      working-directory: ${{ matrix.project }}
      run: |
        gofmt -s -d .

        # If there are any diff, exit as error
        [ "$(gofmt -s -l .)" == "" ] || exit 1

    - name: Build
      working-directory: ${{ matrix.project }}
      run: go build -v ./...

    - name: Test
      working-directory: ${{ matrix.project }}
      run: go test -v ./...

